source:      .
destination: ./_site
# plugins:     ./_plugins
layouts:     ./_layouts
# include:     ['.htaccess']
# exclude:     []
# keep_files:  ['.git','.svn']
# timezone:    nil

production_url : http://adamtilton.com

permalink: /:year/:month/:day/:title 

name: Adam Tilton
pygments: true
markdown: rdiscount


title: TheWoods 
tagline: 
author:
  name: Adam Tilton
  email: adamtilton@adamtilton.com
  github: adamtilton
  twitter: adamtilton



source: .
destination: ./_site
# plugins:     ./_plugins
layouts: ./_layouts
# include:     ['.htaccess']
# exclude:     []
# keep_files:  ['.git','.svn']
# timezone:    nil

analytics:
  provider: google 
  google: 
  tracking_id: 'UA-31831859-1'
